# Generated by go2rpm 1.11.1
%bcond_without check

# https://github.com/rfjakob/gocryptfs
%global goipath         github.com/rfjakob/gocryptfs
Version:                2.4.0

# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
# ---
# New Fedora packages should use %%gometa -f, which makes the package
# ExclusiveArch to %%golang_arches_future and thus excludes the package from
# %%ix86. If the new package is needed as a dependency for another package,
# please consider removing that package from %%ix86 in the same way, instead of
# building more go packages for i686. If your package is not a leaf package,
# you'll need to coordinate the removal of the package's dependents first.
# ---
# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
%gometa -L -f

%global common_description %{expand:
Encrypted overlay filesystem written in Go.}

%global golicenses      LICENSE
%global godocs          README.md Documentation/CLI_ABI.md\\\
                        Documentation/MANPAGE-STATFS.md\\\
                        Documentation/MANPAGE-XRAY.md\\\
                        Documentation/SECURITY.md Documentation/duplicate-\\\
                        inodes.txt Documentation/extractloop.md\\\
                        Documentation/performance-reverse.txt\\\
                        Documentation/performance.txt\\\
                        Documentation/MANPAGE.md Documentation/XFSTESTS.md\\\
                        Documentation/file-format.md gocryptfs-\\\
                        xray/xray_tests/aesgcm_fs.masterkey.txt gocryptfs-\\\
                        xray/xray_tests/aessiv_fs.masterkey.txt gocryptfs-\\\
                        xray/xray_tests/aesgcm_fs.xray.txt gocryptfs-\\\
                        xray/xray_tests/aessiv_fs.xray.txt

Name:           gocryptfs
Release:        %autorelease
Summary:        Encrypted overlay filesystem written in Go

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep -A
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%build
%gobuild -o %{gobuilddir}/bin/gocryptfs %{goipath}
for cmd in contrib/getdents-debug/getdents contrib/getdents-debug/readdirnames contrib/findholes gocryptfs-xray contrib/statfs contrib/statvsfstat contrib/atomicrename; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc README.md Documentation/CLI_ABI.md Documentation/MANPAGE-STATFS.md
%doc Documentation/MANPAGE-XRAY.md Documentation/SECURITY.md
%doc Documentation/duplicate-inodes.txt Documentation/extractloop.md
%doc Documentation/performance-reverse.txt Documentation/performance.txt
%doc Documentation/MANPAGE.md Documentation/XFSTESTS.md
%doc Documentation/file-format.md
%doc gocryptfs-xray/xray_tests/aesgcm_fs.masterkey.txt
%doc gocryptfs-xray/xray_tests/aessiv_fs.masterkey.txt
%doc gocryptfs-xray/xray_tests/aesgcm_fs.xray.txt
%doc gocryptfs-xray/xray_tests/aessiv_fs.xray.txt
%{_bindir}/*

%gopkgfiles

%changelog
%autochangelog
